In [1]:
import numpy as np
from PIL import Image, ImageFile
import pandas as pd
import torch
import os

In [2]:
label_path = "50_examples/labels/2007_000032_jpg.rf.453cf71521fb73718369a7f07a41433c.txt"
img_path = "50_examples/images/2007_000032_jpg.rf.453cf71521fb73718369a7f07a41433c.jpg"

In [3]:
bboxes = np.roll(np.loadtxt(fname=label_path, delimiter=" ", ndmin=2), 4, axis=1).tolist()
image = np.array(Image.open(img_path).convert("RGB"))

In [13]:
ANCHORS = [
    [(0.28, 0.22), (0.38, 0.48), (0.9, 0.78)],
    [(0.07, 0.15), (0.15, 0.11), (0.14, 0.29)],
    [(0.02, 0.03), (0.04, 0.07), (0.08, 0.06)],
]
anchors = torch.tensor(ANCHORS[0] + ANCHORS[1] + ANCHORS[2])
anchors

tensor([[0.2800, 0.2200],
        [0.3800, 0.4800],
        [0.9000, 0.7800],
        [0.0700, 0.1500],
        [0.1500, 0.1100],
        [0.1400, 0.2900],
        [0.0200, 0.0300],
        [0.0400, 0.0700],
        [0.0800, 0.0600]])

In [22]:
targets = [torch.zeros((9 // 3, S, S, 6)) for S in [13, 26, 52]]

In [23]:
def anchor_iou (box_pred, box_anchor):
    w_1 = box_pred[..., 0:1]
    h_1 = box_pred[..., 1:2]
    w_2 = box_anchor[..., 0:1]
    h_2 = box_anchor[..., 1:2]

    w_max = torch.max(w_1, w_2)
    w_min = torch.min(w_1, w_2)
    h_max = torch.max(h_1, h_2)
    h_min = torch.min(h_1, h_2)


    return (w_min * h_min) / ( (w_1 * h_1) + (w_2 * h_2) - (w_min * h_min) )

In [24]:
x = torch.tensor(bboxes[0][2:4])
result = anchor_iou(x, anchors)
x

tensor([0.5420, 0.3737])

In [25]:
result

tensor([[0.3042],
        [0.5845],
        [0.2885],
        [0.0518],
        [0.0815],
        [0.2005],
        [0.0030],
        [0.0138],
        [0.0237]])

In [9]:
from PIL import Image, ImageFile


TypeError: conv2d() received an invalid combination of arguments - got (numpy.ndarray, Parameter, NoneType, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !Parameter!, !NoneType!, !tuple!, !tuple!, !tuple!, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !Parameter!, !NoneType!, !tuple!, !tuple!, !tuple!, int)


In [10]:
image.shape

(343, 500, 3)

In [10]:
import os
os.chdir("/Users/zhangjianan/Desktop/Project/Pascal_VOC_2012")